version: 1

before:
  hooks:
    - go mod tidy
env:
  - CGO_ENABLED=0

builds:
  - binary: go-fis-api
    id: go-fis-api
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
      - .env.example
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Initial trial"
